//
// Created by simon on 04/12/2022.
//

#ifndef ESAMELABORATORIO_COLLEZIONENOTEIMPORTANTI_H
#define ESAMELABORATORIO_COLLEZIONENOTEIMPORTANTI_H


class CollezioneNoteImportanti {

};


#endif //ESAMELABORATORIO_COLLEZIONENOTEIMPORTANTI_H
